# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'gui'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'example'
    ports:
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  my-db:

